security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        account_provider:
            entity:
                class: App\Entity\Account
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            # custom_authenticator: App\Security\AccountTokenAuthenticator
            custom_authenticators:
                - App\Security\AccountTokenAuthenticator
                - App\Security\AccountAuthenticator

            lazy: true
            provider: account_provider


    access_control:
        #- { path: ^/account/create, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/account/update, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/account/delete, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/account/manage, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
